Users/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'Users'

urlpatterns = [
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^register/$', views.UserRegisterView.as_view(), name='register'),
    url(r'^login/$',views.UserLoginView.as_view(),name='login'),
    url(r'^profile/$',views.UserUpdateView.as_view(),name='profile'),
    url(r'^statistics/$',views.StatisticsView.as_view(),name='statistics'),
    
]

games/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'games'

urlpatterns = [
    url(r'^gomoku/$', views.GomokuView.as_view(), name='gomoku'),
    url(r'^gomokuPlayers/$',views.PlayerInGame.as_view(), name='gomokuPlayers'),
    url(r'^gomokuRooms/$',views.GomokuRooms.as_view(), name='gomokuRooms'),
    url(r'^gomokuGame/$',views.GomokuGameView.as_view(), name='gomokuGame'),
    url(r'^gomokuStartGame/$',views.GomokuStartGameView.as_view(), name='gomokuStartGame'),
    url(r'^gomokuGameBoard/$',views.GomokuGameBoardView.as_view(), name='gomokuBoardGame'),
    url(r'^gomokuGame/(?P<room_id>[0-9]+)/$',views.GomokuJoinGameView.as_view(), name="gomokuJoinGame"),
    url(r'^addMessagesToChat/$', views.AddMessagesToChatView.as_view(), name='addMessagesToChat'),
    url(r'^getMessagesFromChat/$', views.SendMessagesToUser.as_view(), name='sendMessagesToUser'),
    url(r'^bridge/$', views.BridgeView.as_view(), name='bridge'),
    url(r'^bridgeGame/$',views.BridgeGameView.as_view(), name='bridgeGame'),
    url(r'^bridgeStartGame/$',views.BridgeStartGameView.as_view(), name='bridgeStartGame'),
    url(r'^bridgeGameBoard/$',views.BridgeGameBoardView.as_view(), name='bridgeBoardGame'),
    url(r'^bridgeGame/(?P<room_id>[0-9]+)/$',views.BridgeJoinGameView.as_view(), name="bridgeJoinGame"),
    url(r'^addMessagesToChatBridge/$', views.AddMessagesToChatViewBridge.as_view(), name='addMessagesToChatBridge'),
    url(r'^getMessagesFromChatBridge/$', views.SendMessagesToUserBridge.as_view(), name='sendMessagesToUserBridge'),
    
]

rafalborekProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('Users.urls')),
    url(r'^',include('mainPage.urls')),
    url(r'^',include('games.urls')),
]

games/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class Room(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    #name = models.CharField(max_length=200)
    #firstPlayer = models.OneToOneField(User,related_name="firstPlayer",null=True)
    #secondPlayer = models.OneToOneField(User,related_name="secondPlayer",null=True)
    arePlaying = models.BooleanField(default=False)
    def __str__(self):
        return "Room " + str(self.id)

class Chat(models.Model):
    """
    for gomoku game
    """
    created = models.DateTimeField(auto_now_add=True)
    room = models.OneToOneField(Room)
    def __str__(self):
        return "chat " + str(self.id)
    
class Message(models.Model):
    """
    for gomoku game
    """
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    chat = models.ForeignKey(Chat)
    message = models.CharField(max_length=200)

    def __str__(self):
        return self.user.username + " - " + self.message 


class GomokuGame(models.Model):

    room = models.ForeignKey(Room)
    board = models.TextField(default="{}")
    gameFinished = models.BooleanField(default=False)
    
    

class GomokuOnline(models.Model):

    user = models.OneToOneField(User)
    online = models.BooleanField(default=False)
    room = models.ForeignKey(Room, null=True)
    wantToPlay = models.BooleanField(default=False)
    readyToPlay = models.BooleanField(default=False)
    playing = models.BooleanField(default=False)
    wins = models.IntegerField(default=0)
    losses = models.IntegerField(default=0)
    draws = models.IntegerField(default=0)
    currentGame = models.ForeignKey(GomokuGame,null=True)
    def __str__(self):
        return self.user.username




class BridgeRoom(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    turn = models.CharField(max_length=200,default="West")
    arePlaying = models.BooleanField(default=False)
    def __str__(self):
        return "BridgeRoom " + str(self.id)
  
  
class BridgeChat(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    room = models.OneToOneField(BridgeRoom)
    def __str__(self):
        return "chat " + str(self.id)
      
class BridgeMessage(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    chat = models.ForeignKey(BridgeChat)
    message = models.CharField(max_length=200)
  
    def __str__(self):
        return self.user.username + " - " + self.message 
  
  
class BridgeGame(models.Model):
    room = models.ForeignKey(BridgeRoom)
    board = models.TextField(default="{}")
    gameFinished = models.BooleanField(default=False)
      
class BridgeOnline(models.Model):
    user = models.OneToOneField(User)
    online = models.BooleanField(default=False)
    room = models.ForeignKey(BridgeRoom,null=True)
    wantToPlay = models.BooleanField(default=False)
    readyToPlay = models.BooleanField(default=False)
    playing = models.BooleanField(default=False)
    wins = models.IntegerField(default=0)
    losses = models.IntegerField(default=0)
    draws = models.IntegerField(default=0)
    currentGame = models.ForeignKey(BridgeGame,null=True)
    side = models.CharField(max_length=200,default="")
    def __str__(self):
        return self.user.username
     
 
     

    

    

games/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponse
from django.views.generic import TemplateView, View
from django.contrib.auth.models import User
from .models import Chat, GomokuOnline, Message, Room, GomokuGame
from .models import BridgeChat, BridgeOnline, BridgeMessage, BridgeRoom, BridgeGame
from django.db.models import Count
import json
from channels import Channel, Group
from games.gomoku.gomoku import *
from games.gomoku.functions import *
from games.bridge.functions import *
from games.bridge.bridge import *
from random import shuffle

# Create your views here.



class GomokuView(View):
    template_name = 'games/gomoku_game.html'
    
    def get(self,request):
        """
        GET request
        :param u: current player in the gomoku game (model GomokuOnline)
        """
        data = {}
        if not self.request.user.is_authenticated():
            return redirect('mainPage:index')
        elif self.request.user.is_authenticated():
            u = GomokuOnline.objects.filter(user=self.request.user)
            if u.exists():
                u = get_object_or_404(GomokuOnline,user=self.request.user)
                #u = GomokuOnline.objects.get(user=self.request.user)
                u.online=True
                if (u.playing == False) and (u.readyToPlay==False) and (u.wantToPlay == False):
                    u.room=None
                u.save()
                
            else:
                u = GomokuOnline(user=self.request.user,online=True)
                u.room=None
                u.save()
            data['room'] = u.room
        return render(request,self.template_name,data)

class GomokuGameView(View):
    template_name = 'games/tic_tac_toe.html'
    
    def get(self,request):
        if not self.request.user.is_authenticated():
            return redirect('mainPage:index')        
        elif self.request.user.is_authenticated():
            u = get_object_or_404(GomokuOnline,user=self.request.user)
            #u = GomokuOnline.objects.get(user=self.request.user)
            if u.playing or u.readyToPlay or u.wantToPlay:
                return redirect('games:gomokuJoinGame',room_id=u.room.id)
            
            try:
                room = Room.objects.annotate(Count('gomokuonline', distinct=True)).filter(gomokuonline__count=0)[:1].get()
            except Room.DoesNotExist:
                room = Room()                
                room.save()
                chat = Chat()
                chat.room=room
                chat.save()
                u.room=room
                u.save()
        return redirect('games:gomokuJoinGame',room_id=room.id)
    
class GomokuJoinGameView(View):

    template_name = 'games/tic_tac_toe.html'
    
    def get(self,request,room_id):

        if not self.request.user.is_authenticated():
            return redirect('mainPage:index')        
        elif self.request.user.is_authenticated():
            u = get_object_or_404(GomokuOnline,user=self.request.user)            
            #u = GomokuOnline.objects.get(user=self.request.user)
            room_id = int(room_id)
            if u.playing or u.readyToPlay or u.wantToPlay:
                if room_id != u.room.id:
                    return redirect('games:gomokuJoinGame',room_id=u.room.id)                    
            room = get_object_or_404(Room, id=room_id)
            u.room=room
            u.save()
            namePlayer = ["Player1", "Player2", "Player3", "Player4"]
            
            players = GomokuOnline.objects.filter(room=room,wantToPlay=True)
            i=0
            
            for player in players:
                namePlayer[i]= player.user.username
                i+=1
        
        return render(request,self.template_name,{'n' : range(15), 'namePlayer1': namePlayer[0], 'namePlayer2': namePlayer[1], 'room': room, 'u' : u})   
     
class GomokuGameBoardView(View):
    def get(self,request):

        if not self.request.user.is_authenticated():
            return JsonResponse({})       
        if self.request.user.is_authenticated():
            u = get_object_or_404(GomokuOnline,user=self.request.user)            
            #u = GomokuOnline.objects.get(user=self.request.user)
            data = {}
            room=u.room
            
            players = GomokuOnline.objects.filter(room=room,wantToPlay=True)
            
            i=0
            namePlayer = ["Player1", "Player2", "Player3", "Player4"]
            data['player1Button'] = True
            data['player2Button'] = True
            data.update({"namePlayer1" : "Player1"})
            data.update({"namePlayer2" : "Player2"})
            for player in players:
                namePlayer[i]= player.user.username
                if i==0:
                    data.update({"namePlayer1" : player.user.username})
                    data['player1Button'] = False
                    if u==player:
                        data['player1Button'] = True
                if i==1:
                    data.update({"namePlayer2" : player.user.username})
                    data['player2Button'] = False
                    if u==player:
                        data['player2Button'] = True                    
                i+=1
            
            if not room.arePlaying:
                if players.count() == 2:
                    if u in players:
                        data['startButton'] = True
                        data['startButtonName'] = 'Start'
                        if u.readyToPlay:
                            data['startButtonName'] = 'Ready'
                    if players[0].readyToPlay and players[1].readyToPlay:
                        players[0].readyToPlay = False
                        players[1].readyToPlay = False                    
                        players[0].playing = True
                        players[1].playing = True
                        data['startButton'] = False
                        data['player1Button'] = False
                        data['player2Button'] = False
                        data['startButtonName'] = 'Playing' 
                        players[0].save()
                        players[1].save()               
                        room.arePlaying = True
                        room.save()
                        game = GomokuGame(room=room,board="{}",gameFinished=False)
                        game.save()
                        players[0].currentGame = game
                        players[1].currentGame = game
                        players[0].save()
                        players[1].save() 
                        board = json.loads(game.board)
                        if board == {}:
                            board["board"] = []
                            Gomoku.fillEmptyBoard(board["board"])
                        game.board = json.dumps(board)
                        game.save()
                        
                        dataToSend = {}
                        dataToSend["board"] = board["board"]
                        Group("gomoku-room-%s" % str(room.id)).send({
                            "text" : json.dumps(dataToSend)
                            })
                        dataToSend["myTurn"] = True
                        Group("gomoku-user-%s" % str(players[0].id)).send({
                            "text" : json.dumps(dataToSend)
                            })
                        dataToSend["myTurn"] = False
                        Group("gomoku-user-%s" % str(players[1].id)).send({
                            "text" : json.dumps(dataToSend)
                            })
                elif u in players:
                    data['startButton'] = False
                    data['startButtonName'] = 'Start'
                    u.readyToPlay=False
                    u.save()
                else:
                    data['startButton'] = False
                    data['startButtonName'] = 'Start'           
            elif room.arePlaying:
                data['startButton'] = False
                data['player1Button'] = False
                data['player2Button'] = False
                data['startButtonName'] = 'Playing'
            
            data['playerResign'] = False
               
            if u.room.arePlaying and u in players:
                data['playerResign'] = True
                

        return JsonResponse(data)   

#     def post(self,request):
#         if not self.request.user.is_authenticated():
#             return JsonResponse({})
#         u = get_object_or_404(GomokuOnline,user=self.request.user)
#         room= u.room
#         data = {}
# #         if room.arePlaying and ((room.firstPlayer==u.user) or (room.secondPlayer==u.user)):
# #             game = u.currentGame
# #             board = json.loads(game.board)
# #             if board == {}:
# #                 board["board"] = []
# #                 Gomoku.fillEmptyBoard(board["board"])
# #                 board["isFirstPlayer"] = True
# #                 
#  
#            
#             
#         
#         return JsonResponse(data)        
        

class GomokuStartGameView(View):

    def post(self,request):
        """
        POST request
        :param u: first player
        :param u2: second player
        """
        if not self.request.user.is_authenticated():
            return JsonResponse({})
        u = get_object_or_404(GomokuOnline,user=self.request.user)        
        #u = GomokuOnline.objects.get(user=self.request.user)
        room = u.room
        buttonPlayer1 = request.POST.get("buttonPlayer1",False) == 'true'
        buttonPlayer2 = request.POST.get("buttonPlayer2",False) == 'true'
        readyToPlay = request.POST.get("readyToPlay",False) == 'true'
        resign = request.POST.get("resign",False) == 'true'
        data ={}
        players = GomokuOnline.objects.filter(room=room,wantToPlay=True)

games/templates/games/bridge.html
{% extends "mainPage/base.html" %}
{% block content %}
{% if user.is_authenticated %}

<div class="container-fluid">
<div class ="clearfix margin-game-buttons">
	<button type="button" id="player1" class="btn btn-primary btn-lg" disabled>{{ namePlayer1 }}</button>
	<button type="button" id="player2" class="btn btn-primary btn-lg" disabled>{{ namePlayer2 }}</button>
	<button type="button" id="player3" class="btn btn-primary btn-lg" disabled>{{ namePlayer3 }}</button>
	<button type="button" id="player4" class="btn btn-primary btn-lg" disabled>{{ namePlayer4 }}</button>
	<button type="button" id="startGame" class="btn btn-primary btn-lg" disabled>Start</button>
	<button type="button" id="resign" class="btn btn-primary btn-lg pull-right">Resign</button>
</div>

<div id="auctionButtons">
<div class="btn-group" role="group" aria-label="...">
  <button type="button" class="btn btn-default auctionOptionPoints">1</button>
  <button type="button" class="btn btn-default auctionOptionPoints">2</button>
  <button type="button" class="btn btn-default auctionOptionPoints">3</button>
  <button type="button" class="btn btn-default auctionOptionPoints">4</button>
  <button type="button" class="btn btn-default auctionOptionPoints">5</button>
  <button type="button" class="btn btn-default auctionOptionPoints">6</button>
  <button type="button" class="btn btn-default auctionOptionPoints">7</button>
</div>
<div class="btn-group" role="group" aria-label="...">
  <button type="button" class="btn btn-default auctionOptionSuit">C</button>
  <button type="button" class="btn btn-default auctionOptionSuit">D</button>
  <button type="button" class="btn btn-default auctionOptionSuit">H</button>
  <button type="button" class="btn btn-default auctionOptionSuit">S</button>
  <button type="button" class="btn btn-default auctionOptionSuit">NT</button>

</div>
<button type="button" id="buttonPass" class="btn btn-default">pass</button>
<button type="button" id="buttonOK" class="btn btn-default" disabled>ok</button>
<div id="auctionResult">...</div>
</div>

	<div class="row">
		<div class="col-xs-12 col-md-5 col-md-offset-3">
			<div class="game-board">
			<canvas id="gameBridgeCanvas" width="1000" height="1000" />
			</div>
		</div>
		<div class="col-xs-12 col-md-4">
		{% include "games/chat.html" %}
		</div>
	</div>
</div>



{% else %}
<p>Please log in</p>
{% endif %}
{% endblock content %}



{% block otherScripts %}
{% load static %}
<script src="{% static 'games/django_csrf.js' %}"></script>
<script src="{% static 'games/bridge.js' %}"></script>
<script src="{% static 'games/bridge_chat.js' %}"></script>
{% endblock otherScripts %}

games/templates/games/bridge_game.html
{% extends "mainPage/base.html" %}
{% block content %}
{% if user.is_authenticated %}

 {% include "games/bridge_player_list.html" %} 

{% else %}
<p>Please log in</p>
{% endif %}
{% endblock content %}

{% block otherScripts %}
{% load static %}
<script src="{% static 'games/bridge_player_list.js' %}"></script>
{% endblock otherScripts %}

games/templates/games/bridge_player_list.html
<div class="container-fluid">
<a class="btn btn-primary btn-lg" href="{% url 'games:bridgeGame' %}" role="button">New Room</a>
{% if room != None %}
<a class="btn btn-primary btn-lg" href="{% url 'games:bridgeJoinGame' room.id %}" role="button">Room {{ room.id }}</a>
{% endif %}

	<div class="row">
		<div class="table-responsive col-sm-6">
			<table class="table table-striped">
			    <thead>
			      <tr>
			        <th>Rooms</th>
			        <th>Online</th>
			        <th></th>
			      </tr>
			    </thead>
			    <tbody id="rooms">
			
			    </tbody>
			</table>
		</div>
		<div class="table-responsive col-sm-6">
			<table class="table table-striped">
			    <thead>
			      <tr>
			        <th>User</th>
			        <th>Room</th>
			      </tr>
			    </thead>
			    <tbody id="playersOnline">
			
			    </tbody>
			</table>
		</div>
	</div>
</div>

games/templates/games/bridge_rooms.html
{% for obj in rooms %}
	<tr>
        <td>{{obj.id}}</td>
        <td>{{obj.num_online}}</td>
        <td><a class="btn btn-primary btn-md" href="{% url 'games:bridgeJoinGame' obj.id %}" role="button">Join</a></td>
	</tr>
{% empty %}
    <tr>
    	<td>...<td>
    	<td>...<td>
    	<td>...<td>
    <tr>
{% endfor %}

games/templates/games/chat.html
    <div id="chat-body" class="panel panel-default">
        <div class="panel-heading">Chat - Room {{room.id}}</div>
        <div id="all-message" class="panel-body scrolling-chat">
            <ul id="message-list" class="list-group">
                    <li class="text-right list-group-item break-text">...</li>
            </ul>
        </div>
    </div>

    <form id="form-to-send-data" method="post" action="/addMessagesToChat/">
    	{% csrf_token %}
        <div class="input-group">
            <input type="text" id="message-to-send" class="form-control"/>
            <span class="input-group-btn">
                <input class="btn btn-default" id="send-chat" type="submit" value="Send"/>
            </span>
        </div>
    </form>

games/templates/games/current_players_online.html
{% for obj in usersOnline %}
	<tr>
        <td>{{obj.user.username}}</td>
        <td>{{obj.room}}</td>
	</tr>
{% empty %}
    <tr>
    	<td>...<td>
    	<td>...<td>
    <tr>
{% endfor %}

games/templates/games/gomoku_game.html
{% extends "mainPage/base.html" %}
{% block content %}
{% if user.is_authenticated %}

 {% include "games/gomoku_player_list.html" %} 

{% else %}
<p>Please log in</p>
{% endif %}
{% endblock content %}

{% block otherScripts %}
{% load static %}
<script src="{% static 'games/gomoku_player_list.js' %}"></script>
{% endblock otherScripts %}

games/templates/games/gomoku_player_list.html
<div class="container-fluid">
<a class="btn btn-primary btn-lg" href="{% url 'games:gomokuGame' %}" role="button">New Room</a>
{% if room != None %}
<a class="btn btn-primary btn-lg" href="{% url 'games:gomokuJoinGame' room.id %}" role="button">Room {{ room.id }}</a>
{% endif %}

	<div class="row">
		<div class="table-responsive col-sm-6">
			<table class="table table-striped">
			    <thead>
			      <tr>
			        <th>Rooms</th>
			        <th>Online</th>
			        <th></th>
			      </tr>
			    </thead>
			    <tbody id="rooms">
			
			    </tbody>
			</table>
		</div>
		<div class="table-responsive col-sm-6">
			<table class="table table-striped">
			    <thead>
			      <tr>
			        <th>User</th>
			        <th>Room</th>
			      </tr>
			    </thead>
			    <tbody id="playersOnline">
			
			    </tbody>
			</table>
		</div>
	</div>
</div>

games/templates/games/messages.html
{% for obj in messages %}
    {% if obj.user == request.user %}
        <li class="text-right list-group-item">{{obj.user}}: {{ obj.message }}</li>
    {% else %}
        <li class="text-left list-group-item">{{obj.user}}: {{ obj.message }}</li>
    {% endif %}
{% empty %}
    <li class="text-right list-group-item">Nothing here...</li>
{% endfor %}

games/templates/games/rooms.html
{% for obj in rooms %}
	<tr>
        <td>{{obj.id}}</td>
        <td>{{obj.num_online}}</td>
        <td><a class="btn btn-primary btn-md" href="{% url 'games:gomokuJoinGame' obj.id %}" role="button">Join</a></td>
	</tr>
{% empty %}
    <tr>
    	<td>...<td>
    	<td>...<td>
    	<td>...<td>
    <tr>
{% endfor %}

games/templates/games/tic_tac_toe.html
{% extends "mainPage/base.html" %}
{% block content %}
{% if user.is_authenticated %}

<div class="container-fluid">
<div class ="clearfix margin-game-buttons">
	<button type="button" id="player1" class="btn btn-primary btn-lg" disabled>{{ namePlayer1 }}</button>
	<button type="button" id="player2" class="btn btn-primary btn-lg" disabled>{{ namePlayer2 }}</button>
	<button type="button" id="startGame" class="btn btn-primary btn-lg" disabled>Start</button>
	<button type="button" id="resign" class="btn btn-primary btn-lg pull-right">Resign</button>
</div>
	<div class="row">
		<div class="col-xs-12 col-md-5 col-md-offset-3">
			<div class="game-board">
				{% for i in n %}
					{% for j in n %}
						<div id="cell-{{i}}-{{j}}" class="cell"></div>
					{% endfor %}
				{% endfor %}
			</div>
		</div>
		<div class="col-xs-12 col-md-4">
		{% include "games/chat.html" %}
		</div>
	</div>
</div>


{% else %}
<p>Please log in</p>
{% endif %}
{% endblock content %}



{% block otherScripts %}
{% load static %}
<script src="{% static 'games/django_csrf.js' %}"></script>
<script src="{% static 'games/tic_tac_toe.js' %}"></script>
<script src="{% static 'games/chat.js' %}"></script>
{% endblock otherScripts %}