Users/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'Users'

urlpatterns = [
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^register/$', views.UserRegisterView.as_view(), name='register'),
    url(r'^login/$',views.UserLoginView.as_view(),name='login'),
    url(r'^profile/$',views.UserUpdateView.as_view(),name='profile'),
    url(r'^statistics/$',views.StatisticsView.as_view(),name='statistics'),
    
]

games/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'games'

urlpatterns = [
    url(r'^gomoku/$', views.GomokuView.as_view(), name='gomoku'),
    url(r'^gomokuPlayers/$',views.PlayerInGame.as_view(), name='gomokuPlayers'),
    url(r'^gomokuRooms/$',views.GomokuRooms.as_view(), name='gomokuRooms'),
    url(r'^gomokuGame/$',views.GomokuGameView.as_view(), name='gomokuGame'),
    url(r'^gomokuStartGame/$',views.GomokuStartGameView.as_view(), name='gomokuStartGame'),
    url(r'^gomokuGameBoard/$',views.GomokuGameBoardView.as_view(), name='gomokuBoardGame'),
    url(r'^gomokuGame/(?P<room_id>[0-9]+)/$',views.GomokuJoinGameView.as_view(), name="gomokuJoinGame"),
    url(r'^addMessagesToChat/$', views.AddMessagesToChatView.as_view(), name='addMessagesToChat'),
    url(r'^getMessagesFromChat/$', views.SendMessagesToUser.as_view(), name='sendMessagesToUser'),
    url(r'^bridge/$', views.BridgeView.as_view(), name='bridge'),
    url(r'^bridgeGame/$',views.BridgeGameView.as_view(), name='bridgeGame'),
    url(r'^bridgeStartGame/$',views.BridgeStartGameView.as_view(), name='bridgeStartGame'),
    url(r'^bridgeGameBoard/$',views.BridgeGameBoardView.as_view(), name='bridgeBoardGame'),
    url(r'^bridgeGame/(?P<room_id>[0-9]+)/$',views.BridgeJoinGameView.as_view(), name="bridgeJoinGame"),
    url(r'^addMessagesToChatBridge/$', views.AddMessagesToChatViewBridge.as_view(), name='addMessagesToChatBridge'),
    url(r'^getMessagesFromChatBridge/$', views.SendMessagesToUserBridge.as_view(), name='sendMessagesToUserBridge'),
    
]

mainPage/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'mainPage'
urlpatterns = [
    url(r'^$',views.index,name='index'),
]

rafalborekProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('Users.urls')),
    url(r'^',include('mainPage.urls')),
    url(r'^',include('games.urls')),
]

mainPage/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

mainPage/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from django.views.generic import View
# Create your views here.

def index(request):
    """
    home page
    """
    return render(request, 'mainPage/index.html',{ })





  

mainPage/templates/mainPage/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}Hi all{% endblock title %}</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
	integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
	crossorigin="anonymous">

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mainPage/style.css' %}">
</head>

<body>
	{% block body %}

	<nav class="navbar navbar-inverse navbar-static-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed"
					data-toggle="collapse" data-target="#navbar" aria-expanded="false"
					aria-controls="navbar">
					<span class="sr-only">Menu</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'mainPage:index' %}">PlayGames :)</a>
			</div>
			<div id="navbar" class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
				</ul>
				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
					<li><a href="{% url 'Users:statistics' %}"><span class="glyphicon glyphicon-stats"></span>
							Statistics</a></li>
					<li><a href="{% url 'Users:profile' %}"><span class="glyphicon glyphicon-user"></span>
							Profile</a></li>
					<li><a href="{% url 'Users:logout' %}"><span class="glyphicon glyphicon-log-out"></span>
							Log out</a></li>
					{% else %}
					<li><a href="{% url 'Users:register' %}"><span class="glyphicon glyphicon-user"></span>
							Sign Up</a></li>
					<li><a href="{% url 'Users:login' %}"><span class="glyphicon glyphicon-log-in"></span>
							Log In</a></li>
					{% endif %}
				</ul>
			</div>
			<!--/.nav-collapse -->
		</div>
	</nav>


	{% block content %}
	
	{% endblock content %}

	{% endblock body %}


	<!-- jQuery -->
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

	<!-- Latest compiled and minified JavaScript -->
	<script
		src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
		integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
		crossorigin="anonymous"></script>
	{% block otherScripts %}{% endblock otherScripts %}
</body>

</html>

mainPage/templates/mainPage/index.html
{% extends "mainPage/base.html" %}
{% block content %}
{% if user.is_authenticated %}
<div class="container">
	<div class="jumbotron">
	  <h1>Hi {{ user.username }}</h1>
	  <p>Choose the game you want to play</p>
	  <p><a class="btn btn-primary btn-lg" href="{% url 'games:gomoku' %}" role="button">Gomoku</a></p>
	  <p><a class="btn btn-primary btn-lg" href="{% url 'games:bridge' %}" role="button">Bridge</a></p>
	</div>
</div>
{% else %}
<div class="container">
	<div class="jumbotron">
	  <h1>Hi!</h1>
	  <p>To see games log in or sign up</p>
	  <p><a class="btn btn-primary btn-lg" href="{% url 'Users:login' %}" role="button">Log In</a> <a class="btn btn-primary btn-lg" href="{% url 'Users:register' %}" role="button">Sign Up</a></p>
	</div>
</div>
{% endif %}
{% endblock content %}